"""Initial migration

Revision ID: 843442ae3dbc
Revises: 
Create Date: 2024-03-04 13:01:08.841167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843442ae3dbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enumerators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('garbling_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shocks', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('global_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('Respondent', 'Enumerator', 'Admin', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('respondents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('response_status', sa.Enum('Complete', 'Incomplete', name='responsestatus'), nullable=False),
    sa.Column('enumerator_uuid', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['enumerator_uuid'], ['enumerators.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('survey_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response', sa.String(), nullable=False),
    sa.Column('respondent_uuid', sa.String(length=36), nullable=False),
    sa.Column('enumerator_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['enumerator_uuid'], ['enumerators.uuid'], ),
    sa.ForeignKeyConstraint(['respondent_uuid'], ['respondents.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('respondent_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('survey_responses')
    op.drop_table('respondents')
    op.drop_table('users')
    op.drop_table('global_states')
    op.drop_table('garbling_blocks')
    op.drop_table('enumerators')
    # ### end Alembic commands ###
